language: android

android:
   components:
   - tools
   - platform-tools
   - android-25
   - build-tools-25.0.0
   - extra

jdk: oraclejdk8

notifications:
  email: false

before_install:
   - touch local.properties
   - source gradle.properties
   - source .travis/env.sh
   - openssl aes-256-cbc -K $encrypted_75846693d905_key -iv $encrypted_75846693d905_iv -in release.jks.enc -out release.jks -d

script:
  - ./gradlew clean assembleDebug
  - cp app/build/outputs/apk/CallerInfo-v$VERSION_NAME-debug.apk $HOME
  - cp plugin/build/outputs/apk/CallerInfo-plugin-v$PLUGIN_VERSION_NAME-debug.apk $HOME
  - ./gradlew clean assembleRelease
  - cp app/build/outputs/apk/CallerInfo-v$VERSION_NAME-release.apk $HOME
  - cp plugin/build/outputs/apk/CallerInfo-plugin-v$PLUGIN_VERSION_NAME-release.apk $HOME
  - md5sum "$HOME/CallerInfo-v$VERSION_NAME-debug.apk"
  - md5sum "$HOME/CallerInfo-v$VERSION_NAME-release.apk"
  - md5sum "$HOME/CallerInfo-plugin-v$PLUGIN_VERSION_NAME-debug.apk"
  - md5sum "$HOME/CallerInfo-plugin-v$PLUGIN_VERSION_NAME-release.apk"
  - sha1sum "$HOME/CallerInfo-v$VERSION_NAME-debug.apk"
  - sha1sum "$HOME/CallerInfo-v$VERSION_NAME-release.apk"
  - sha1sum "$HOME/CallerInfo-plugin-v$PLUGIN_VERSION_NAME-debug.apk"
  - sha1sum "$HOME/CallerInfo-plugin-v$PLUGIN_VERSION_NAME-release.apk"

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file:
    - "$HOME/CallerInfo-v$VERSION_NAME-debug.apk"
    - "$HOME/CallerInfo-v$VERSION_NAME-release.apk"
    - "$HOME/CallerInfo-plugin-v$PLUGIN_VERSION_NAME-debug.apk"
    - "$HOME/CallerInfo-plugin-v$PLUGIN_VERSION_NAME-release.apk"
  skip_cleanup: true
  on:
    tags: true

env:
  global:
    # GITHUB_TOKEN
    - secure: "YHusmrbBBq4JsT0pVkwgDlpg3GB+Tql50BCPMz9KwRuqk7YBaV1k6dtac5mKLT2W+Qc8ZLx4JsqmC6wSEEOyf/prkjgitKlDU0WKl8k1qi46m/aV9O5o0/2z3QUJgPv0jYxfggAcGNaz+XNmguyd5I4YtBfgwP0arGNKNmBc4HcyArx+PHslTkxI9ua0darrGLkhMCd+9WNdInhk5B39wZPycNS2JpX2CBXSKK5TvnKEY97cj9sUmv0tRG1+/yyOYjzB71AHTPfMm+iZIIAS4Q4/GG+9frFDzdmif9Ae/Xhwo2K7LGyS9Uh62nxf0TO5o9NvhqSYgvGFMt+ihhntMBau1cO+nCTL3r5e5TXTZfwi9DqEP/DY0HNnsitDvwp7xLnScZkqQ5wCnyrxClGxhawmyofLw+u7Yf3fvn/lfyDwwygfnbuMdWV0wjezy5i9HEYFzUJKWBwEC7ds5e350e0Fshq0Ac8SDHKwOLCqwaSgf3a0vuFk5SNaL63cBBWLXgOPpsHByyxitrAtk8lTc5PQDoqD5/bvZcCqEFyXvLhgOj+KSqfSgItBy8/+30dtAq0i3iI6e5vk35IQZi/qTosN+gycTf21MY16vMDvUgbUWP1UnACA4i6XT1r/ccimozN8c9y/MxVT2GBTdijGghMpHCTruceudP9uUraltH8="
    # KEYSTORE_PASSWORD
    - secure: "p8Fo+3roFxsaZiZvEeHG5L3uj/2H91dWRKqayvdDXmBN2fgWR0ONQ++Mhl2kSE4gUL6ZJiaSBRrNOQZXVJasilmYkTRizv1lG8vuVdZ5aNALki44vsVRIuklvsFwk/BvaeH9Vfc3kRq1hSdJDLQPGzPOPAxNkXxXJ/NloqRWC5AMd+e8L+MbwxVahEVsT/lYpgG/F3nUbd48D4UsooF9IdvPOrAipHhOXhxIMwNPdxhMjDHQF2sVDDM8Z3UnX1jvlleoHxnm1V8AjgH54HtI9fFS+q/5N5uJmp7z5RaUzDnGOb1m4kMtMAOfLSwrCKRq/NH9HF2fiK6JHIDEoeUlaqD4+O8fVPtBofxoQlM+kROK+Fkvop+pF2Wqkyw0x8Gx+O4GRiexE5zrGCfhKYgiB+DwSCxGCSAbRotOgWG63ohzN3PTH/bLvMuyuyv/w0b13FoA3oOtH3aZb24FEkZxl20TPZSvdQfSn7O5dH4ybnbEK56QS08Xtvq8d+xHEcaDk+FUfeHeT8laPghH72nq+Y/dSJ0Cuu/Z1cGScvy6AmC/2Ibn2b4QLQluNfSc2nMhDFxWj6fzSezezwdvwuof7XXHeZjuKPpm6+ARz/PgCd5z4VkcW1vl/rbEIctDaefqyCS6tiw2Dm9rL6GEwDw161GTAP5H1fdmNgcZqZ9EdfI="
    # ALIAS_PASSWORD
    - secure: "GVIPM+9k0PrZd/hGN1DHpcWVjSV35ELEqUbccAP1B7PmyHK5ylqvMZ2ptpRZJFzfMTsGbXxgxaAeH4ErMlTDDIs+ar8n2nQ9KzXk+MUWdGNVxTHmyJzysh8Awz4UXCvHDU9uTlVOqO2O8y4Qcmj1m2sRHoZzoMLVmgWxfwfp856pda8XHqbA9OUCaPqMKszY4tjm/5Lrm06xNO9qDB/X5LS/Ssff4Ad0XDXr9g5WuXMTrzmdsf0XkbBXr3YTNDb+rFQTz4uaDCqCdIEycsI9Z+etW/Y7HglOkIHf2kIevl1kO4m3u7kZnOdVpXtK+w4OYJbxBN9d874ieIkbFYlAl6yPxMv6RlVjqlDtHH1IryPeRB8chuRaGjyy/FQjaQbt9aXh2NKCMsI2LdjSsayoIUgSKz5SR4QejCnFzqnfT+KGEFE+sadIrgO3XTOrjINOu6WWiA/O4vTHK8H9mznTAwM3vf8+kBupi86CundLbi7J8e2gKGjYBAVISO8IzCs0qJ+wokoZJWdU7uCNS+v+/7mpas63JVpm2i6z2S0ZSHhkNp+lVQV6KLROY1AOMfvZEWWCll9GawVMHsaJ9l4v37ZzP5LUkhbQgT7awi0SVz/CQ/swFgq7efiSguZeUYKHz6i0AUugT6Fs1dRvGy5H7IoeucDkxq5bkJShcGLrSR0="
    # ALIAS
    - secure: "Ircx5pWaD0OG3UfKG7M3KiZ+7gC2Vuv7TjJ+GR1pQMzhDOweEoFZ/Tz9pVqkn/VSVHpVwHpLsh5FRJIsWXb9fSJiMerNMBkpWZdsabYNvbNiNE5G6UYyJtM23Z3qXQIDMjh/8Xc75/7SYDN6tvP3c5Bo3J/Cmjr/Y2H9BOqoOdAnC+b6RYtXtfsClRR9goPRKz6Roz//SEtRwSfJJI1+Y/NNOwJn8OXLChIwy/sG0Lles33Ykceb/ISJ2yFwfl6m0xQ19A64qxqjHo5E1XeyyqsxmYTwhDly7kxIsWf+xtpooMZzd5Y2EW97hx8+KMjeonJwki7TLvCt++XZRcI/8ELIf34v5cqSi2LiKdEhOhpf8LnARCnHccFmErg1FNkjpMzQyfAf4LqzXRdynSyfb6y51sj9KKltcdAld9OMn00FfY0s9CAxQqpIQzubToVBx2KM21PBX17Pyf8Ss2oJnMIaQacZKMO4XHSlh6cIqc/zS94Wup++8IxgG+ZawFtbohtQwoNAJLCxAibquQ/eNnl+rOQL8hrO/9Aou98Tfi+l2RNxSo1nA0J7UeHf11n+4WQw3GC+BR41/3MWTAcQLskt4P3zr9FhdMpdfN1/JxU6+WcV3JlS8io3zZD2FKd9GbkL67PG4DtpKVohr7lQkKq4lx6o2qZlMSliC+2mGb8="
    # API_KEY
    - secure: "Guf+ItqSTPN9l/yy/pOfbtzpu7G2lBbUZW8ghio/uSUyvbvwB9/tfzV+1TklC+G3x8WgQfD37oEOcxZuBIqTSDw+/7+nwLkMsUh5KjIJwj7Il6EVls+EWKUg7DtNHzduIr6F6tab8/6Gbv2rdKuvksuKZqLQuX6jpzpedXge5s+5RqoBDpNtlnrUmSdBJzIUr12eGvXPcGqEVStYocYszXFAN+7sgiE8C5MvtifYks5M3ZQTX+1HuJq+HcLn1Xbc4zZcZACh22nmFt0dTkmEcc3wYJndSBSv/gbFljMTYZ5hcZXT3Lm2cJI21sZCB+cQ/Cj9TrzhKTZQISNZ4Jx7R1i4udc2105Li8D0/hY6Aix9TNl050AvbmlKGTcLQJLqC+SiSfBmWWMWKs6JsgWePjMEfOVV0zgYfOWK1HeTqcjzLTYaI6JEwmZ/hXP+phDl+QiqmztPbhq4CXbP3Tzq4mF0Mi9vfuxs7HECFxYIniIHVJ09GyVZiSUdOajzBpVBY+euXMQZHWJ81phG/oNpaZSsbsZck2MjoeVt2o6UMV3htpLsRcEuY2Sml9RS9NbGIz9N36MlsepXFLmoaEFtl8w2OH9V/vy5+HWPCpJPAUzk9S1wSlJdeEibycVWSktkIUm/6gB3g5jL3SRblcP+ELpKdiqdJx5U1OBfw9b8YS4="
    # JUHE_API_KEY
    - secure: "oHyoYHAga1k4Q/rcj0cgVpl5tE1yw3dCoVuF1F9l4sNv43ycrXrP8oKE68UFGzseXCEg4lAZaRoz5uVmGUbmKZV3Dv6MO5mQR+i+OaeUxMag4FOUt7bP7iM9F/xqoSG5/ZOVomYHoKhUEE3oQYsnQuNwcpk66VdeMTUaiXgDuVRCCNe5wUrgwsuuGVsMqxIVi+hW8qEKO5wqQyuB/Fwm+dz9jL6XGtopILxyJpiptpQtnkusOxG4JJ3aERw//CavOO62Q2blsQ2wpnyL7tdJnh6LVUmZFDFwFVUytRPC3Yeqmb32umn47srhAXFpFggV9jDdYDDteTjSKw26GvM9PHXNwyPlMtsXXYrpfXcCE1dv9V+HMqkUbHMjSoM/RgnaNUtEBa8JHbJIS2KBKrF06foodIm0TvQO/lc6uKpcx7g65ntHp9WwqM1JcFfFLgiwasRGfQKw7xrPjy8C7F2jYpUJTtaz44mn3TlqI2ITlFgTIp57w3JkdpEFxNg0TlqdBIuH4WbXuFBNy/BfLNikiRlYSqiJGuWq3feFdZlDQT78UJr5nnZQKwT5F9bHzyRW+4qYE+EwOApeGNhewBPpPEBthQaV1atomBzXK9XLywr/bZmxlVMAJOMjBmGS4KfmeIRzmn6GR1A7kHgBgIqCvPjPT3PAGNmXVi1imkyprzo="
    # LEANCLOUD_APP_ID
    - secure: "GLvOiT17vzvUPDfOwLcBAQk9khjQIRssz1meNhRWUZy7A3cUBkuBun8Wh2MtONh23L0LlhZF6weKVzqX0GmRF/yjAXFTw0ulGylz1VFKiGGP0eq6yIJOXVY4AHPqs9LM3Spvx4Wev5u4s/z2OSxGh6LmLMcFFi8wPo414h4WoOIXYtwg+4eaZ3SRXGkGL2mdO3x0QklKGAHGCqyUCEuscPVVXn7CdjtFCODpbeo7SAKpucym4FWpZkplLdpEePaBEQfbXxeCfulf1ADT2PbC1iNziFAIZ/o4lKAoAvX+ZLHlf5Ge9iXSs6I2K7O5hv2nTYZb++gdYOSGby6c2XK4BKUggLBlBeBgEjlAuvWvkZKxwUzTqMqG5n4biwcI5y7dowW/olHQ8iWscOdNneisfecDu+Q2YhvyQPEDNHrmj20Sk6jcLwFqePF/CYGpBoljAJlU1KLouGw0fAWqYCJs6q3AAbaKQO9XYwi8HBOKJ1ZPafiKVkKLjWLuUBYp7a2kJScb6P2jbksWP00D/Nkwo5CmfUDsuM/TaFuA23xfvE3X/3wQse/6nFPjt6AhKEqwOOvzXtUmwktUaycyh1SXkA194sf60eN3n+IG1QhZ58P5kUOvAzPofyIO4PGvs2KMmI/yjwGBJZ2OxCA9XBF4x5KsNp6Ygp+rdxuMwvhmLNw="
    # LEANCLOUD_APP_KEY
    - secure: "ksg39+T1q6ffx4Pvmd6h6XXQD/SAdsd3F25Go8tyr70KBwnVamXAtfAz2j4kjXuzu52YhRXWWwnpgPfKOIAtKGdQE2SxI2UOaNkDS2BL7qQwi8h5Qz7uSW/T01eDxWqcr4uySQ+6AcYtrppQGbIs2rBgc9K6LykVnITMFnzpr98V9IlryHTJ7ZRbQ/4vdIPN+E5S0Vr/Aag5YPZMxg4apGRSn3GGMRM41JbV+Fy6gP65FZTnZtNBKYZuJ2rrnuUROepncMXBBuTYSlZOHYwwSKYQl35Z5KS5vRnLgab/H9J3gjEmVzYxKTpl/YqHqeE6OjG1B4p/kfmpIZFYZGeeRK+yjhOFuxt3NcPy7Xv4WYbcCs3i+sfKCA3BIdTx5vYktws4Ky1XUgqMuvvfxiDezozl7DqIE8b1BHJV6Jq/BDZRDjQKfw69b1UQQZIGbKxv+Nnmk/Bu1P7EQGOAloox3TsBm1XSHySc9aFYacJZVrecAhMInZu8NJa3YsYBOWuNcXGTwty7CRDyQ1TJAXLq4qHX6FoHHPjG7ZLz55YGlcQJgLJvFQLPqvwj6K5vC0RZs23YqmwZRFawtNOThQRyYOSW/XHSugCXS9BXnrOauwzNJFMNbYQv1KRAmQ/qcC2xZvHH3ED2/bz0POUmz+k1tq6pIaUhwEQJG3QWtnNbqHU="
